### ISSUE TITLE
What's about integrating ctxx

### ISSUE THREAD

**Issue by ghost** [Cinderella-Man/toretto#47]
The ccxt standard will help you get many exchanges integrated at once. There is an elixir lib someone started to build but stopped on the way. I was thinking you might not now about ccxt and I wanted to share this with you.

https://github.com/ccxt/ccxt
https://hex.pm/packages/ccxtex

**Comment by Cinderella-Man** [comment]
That's a great share, thank you very much :+1: I will leave this bug open as a reminder that I should investigate CCXT whenever I will come around to integrate more exchanges. Thanks once again!
